# Generated by Django 2.2.6 on 2019-10-19 16:02

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
